export const ME_ACTION = {
    SUCCESS  : 'ME_ACTION_SUCCESS',
    FALIED  : 'ME_ACTION_FALIED',
};
export const LOGIN_ACTION = {
    SUCCESS  : 'LOGIN_ACTION_SUCCESS',
    FALIED  : 'LOGIN_ACTION_FALIED',
};
export const REGISTER_ACTION = {
    SUCCESS  : 'REGISTER_ACTION_SUCCESS',
    FALIED  : 'REGISTER_ACTION_FALIED',
};
export const LOGOUT_ACTION = {
    SUCCESS  : 'LOGOUT_ACTION_SUCCESS',
    FALIED  : 'LOGOUT_ACTION_FALIED',
};